### ISSUE TITLE
Opinion about create a configs to React.js ?

### ISSUE THREAD

**Issue by adimircolen** [editor-bootstrap/vim-bootstrap#201]
I'm thinking about create some config based on frameworks as rails, reactjs.
What are your opinion about this ?

**Comment by cassiobotaro** [comment]
I like the idea, but at the same time https://github.com/avelino/vim-bootstrap/issues/101 can be a more flexible way to treat especific framework plugins.

**Comment by cassiobotaro** [comment]
As frameworks support was implemented, I think this issue can be marked as solved.
