### ISSUE TITLE
Website theme 2.0

### ISSUE THREAD

**Issue by avelino** [editor-bootstrap/vim-bootstrap#284]
We need to think of the 2.0 version of the site, the idea of this issue is exposing ideas.

**Comment by jtemporal** [comment]
two cents here: maybe link the "Contribute" button to [CONTRIBUTING.md](https://github.com/avelino/vim-bootstrap/blob/master/.github/CONTRIBUTING.md) would be a nice thing to have =)

**Comment by avelino** [comment]
- Additional plugins - #101
- - List all the plugin we install for the given language (aesthetically think it is best shows after selecting the language)
- - Support installing other plugin not listed in languages (we can use https://vimawesome.com, ref https://github.com/vim-awesome/vim-awesome/issues/65)
- - Multi theme support - #80
- New visual identity (logo) for the project (possibility of making stickers and t-shirts)
- Redesign (site is already a few years old, we can give a new interface)

**Comment by lerrua** [comment]
Great! I really like these ideas @avelino and I believe that will be increase vim-bootstrap project. But we can't forget about the novice user that just want a kickstart configuration without choose plugins, themes etc. Maybe we can split it in two features, a kickstart mode (or a novice mode) and a advanced mode where user can choose plugins, theme and may see the vimrc preview before download it.

**Comment by cizordj** [comment]
Something that I miss on the website is a list of dependencies, I always head over to the github repo to copy & paste the commands.
