### ISSUE TITLE
Conflict: elm-vim and vim-polyglot

### ISSUE THREAD

**Issue by andys8** [editor-bootstrap/vim-bootstrap#302]
- Vim bootstrap version(number in first line): 89346c6
- Operating system: Ubuntu 16.04 xenial
- Vim/Nvim version: 8.1 
- Languages:  "elm,haskell,html,javascript,scala"

## Description

Opening an `elm` file leads to:
> Error detected while processing function <SNR>90_cmd[15]..fzf#run[69]..<SNR>90_callback: 
> Vim(let):E117: Unknown function: elm#FindRootDirectory

Having done some research, this is a known issue with `vim-polyglot` that can be resolved by changing the order: https://github.com/ElmCast/elm-vim/issues/133#issuecomment-333317387

I know it can be a bit weird because of the ordering in the config file (where `vim-polyglot` is mandatory and `elm-vim` is optional), but I guess it has to be implemented if `elm` is used.

**Comment by andys8** [comment]
Is it possible to change the order?

**Comment by andys8** [comment]
We could also use `vim-polyglot`, and _not_ disable elm. Because `vim-polyglot` is using the same `elm-vim` plugin itself and is working fine.

https://github.com/sheerun/vim-polyglot/blob/9fd5c11a20f88525088c8635a3bc6a25ec4c05c7/build#L181

**Comment by cassiobotaro** [comment]
solved with #359
