### ISSUE TITLE
how to remove php close label "?>"

### ISSUE THREAD

**Issue by buffge** [editor-bootstrap/vim-bootstrap#318]
- Vim bootstrap version(number in first line):
- Operating system: ubtun18.04
- Vim/Nvim version: 8.0
- Languages: php

## Description

When l edit a php file ,init content is <?php xxx ?>
The php file don't need "?>"

**Comment by avelino** [comment]
@buffge I believe your need can enter the local custom file (in your configuration)
I can not assess if it is interesting for the precise design of the staff who contributed to the PHP version, if you can send pull request with the implementation?

@lerrua @cassiobotaro 
php helpers: @eminetto @duodraco
