### ISSUE TITLE
improve windows automatical

### ISSUE THREAD

**Issue by NewUserHa** [editor-bootstrap/vim-bootstrap#320]
- Vim bootstrap version(number in first line):
- Operating system: win10
- Vim/Nvim version: gvim8.1
- Languages: en
automatical
## Description

on windows, 32bit gvim has to use `%windir%\Sysnative` to call `curl`.(64bit has not)
I want to PR but not familiar with vim script.
hope you guys can help fix it, thanks!

**Comment by NewUserHa** [comment]
I figured out the way.
do you need pr?

**Comment by avelino** [comment]
send PR

**Comment by NewUserHa** [comment]
https://github.com/avelino/vim-bootstrap/pull/321

**Comment by cassiobotaro** [comment]
solved in #321
