### ISSUE TITLE
fixed Go path package use

### ISSUE THREAD

**Issue by avelino** [editor-bootstrap/vim-bootstrap#328]
Change repo of **org** `github.com/avelino` to `github.com/editor-bootstrap`

**Comment by mskadu** [comment]
Hello, spotted this on codetriage. 

Isn't this something only the owner of a repo can do? Unless I am misreading this completely.

**Comment by mskadu** [comment]
Also .. it does look like this is already sorted?

**Comment by cassiobotaro** [comment]
solved in #338
