### ISSUE TITLE
dracula theme by default

### ISSUE THREAD

**Issue by avelino** [editor-bootstrap/vim-bootstrap#337]
what do you think of putting Dracula as the default theme?

https://github.com/dracula/vim

**Comment by avelino** [comment]
@cassiobotaro @lerrua

**Comment by cassiobotaro** [comment]
Why not implement a chooser, with screenshots? I will work on it in next week.

**Comment by avelino** [comment]
> Why not implement a chooser, with screenshots? I will work on it in next week.

Excellent option, so we can support in more themes 🍾

**Comment by cassiobotaro** [comment]
Solved with 6d9850259db00337c26469897bf7993e9ecb89e9
