### ISSUE TITLE
Do we have a keyboard shortcut to show the tooltip

### ISSUE THREAD

**Issue by zongUMR** [editor-bootstrap/vim-bootstrap#340]
**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- Vim bootstrap version(number in first line):latest
- Operating system:Mac os latest
- Vim/Nvim version: 8.2 Vim
- Languages: English

## Description
When we input some syntax, it will open a dialog to show some useful message on a dialog. like`console.log()`, 
<img width="719" alt="Screen Shot 2020-09-05 at 08 36 04" src="https://user-images.githubusercontent.com/11454175/92293012-dbab1300-ef52-11ea-9985-89fdf77e840d.png">
Do we have any idea or shortcut to show this dialog in normal or insert mode? I use vim and the versions of anything  are latest

**Comment by avelino** [comment]
@zongUMR did you get it right? Used which plugin?

**Comment by zongUMR** [comment]
I just bind a custom shortcut to function `LspHover`

**Comment by zongUMR** [comment]
<img width="374" alt="Screen Shot 2020-09-06 at 18 32 17" src="https://user-images.githubusercontent.com/11454175/92323944-51a49c80-f06f-11ea-8630-e36766ec0cbd.png">
Like this

**Comment by steelx** [comment]
works with CoC as well. for Rust :1st_place_medal:
