### ISSUE TITLE
Change themes not possible after installation

### ISSUE THREAD

**Issue by flyingrocket** [editor-bootstrap/vim-bootstrap#364]
- Vim bootstrap version(number in first line): latest
- Operating system: Ubuntu 20.10
- Vim/Nvim version: vim 8.2
- Languages: python, javascript

## Description

The initial install worked fine. In this example i used the molokai theme. However, if i wanted to change the theme. So i downloaded another generated file (codedark). I replaced the first vimrc file with the new one. However this didn't work, the theme cannot be found. I tested also with other themes. Same result.

**Comment by cassiobotaro** [comment]
https://github.com/editor-bootstrap/vim-bootstrap-updater/commit/55d9d5794a391cd23f9c0d76336a30aeac0e9c70 will solve your problem. If not, please reopen this issue.
