### ISSUE TITLE
Error detected while processing BufWinEnter Autocommands

### ISSUE THREAD

**Issue by kunthar** [editor-bootstrap/vim-bootstrap#406]
- Vim bootstrap version(number in first line):
" vim-bootstrap 2022-03-23 18:41:31

- Operating system:
Darwin  21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64
Monterey

- Vim/Nvim version:
vim 8.2.4550

- Languages:
go, python, rust

## Description
```
Error detected while processing BufWinEnter Autocommands for "*"..function <SNR>79_Setup[6]..<SNR>79_IndentLinesEnable[10]..<SNR>79_SetConcealOption:
```

necessary tooling already been installed per language. 
using asdf for go!

**Comment by uggla** [comment]
I get the same error and it seems related to indentLine plugin.
https://github.com/Yggdroot/indentLine/issues/369

**Comment by kunthar** [comment]
for anyone needs quick solution, 
comment this line. vim-plug smart enough to disable it.
vi .vimrc
```
 " Plug 'Yggdroot/indentLine'
```

closing this...
