### ISSUE TITLE
Dracula theme with brown background

### ISSUE THREAD

**Issue by jantoniosf** [editor-bootstrap/vim-bootstrap#410]
My system:
- vim-bootstrap 2022-08-04 13:02:53
- Operating system: Debian 11
- Vim/Nvim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 01 2021 01:51:08)
- Languages: Python, HTML

Description
Hi,
I downloaded my .vimrc on vim-bootstrap website with Dracula theme, for my surprise the background was brown after install the theme.
![Dracula_Baixado](https://user-images.githubusercontent.com/11323642/183252211-c7b37310-be87-46e6-a502-6dcecfa257e3.png)

Search on internet I found [way to correct this "problem".
](https://github.com/dracula/vim/issues/65#issuecomment-378773423)

![Dracula_Corrigido](https://user-images.githubusercontent.com/11323642/183252217-a4283d6f-16cf-4f0d-a10b-e74bd424a3ec.png)

Can you add this line of code on  new branch of vim-bootstrap.
**let g:dracula_colorterm = 0**
colorscheme dracula

Thanks

**Comment by avelino** [comment]
Can you send the patch?
