### ISSUE TITLE
Order of commands in dracula theme does not apply background colour well. If you change the order, it works

### ISSUE THREAD

**Issue by nikola-jokic** [editor-bootstrap/vim-bootstrap#422]
- Vim bootstrap version(number in first line): 1.21.10
- Operating system: 22.04.1 LTS 
- Vim/Nvim version: NVIM v0.6.1
- Languages: N/A

## Description

Ordering in file https://github.com/editor-bootstrap/vim-bootstrap/blob/70b17fb40701d640bd0cb3ad2b8b5cef32b6dda4/generate/vim_template/themes/dracula/dracula.vim seems to be wrong. If left like this by default, coloring looks like: 
![image](https://user-images.githubusercontent.com/97525037/200771775-a0b9e37c-2f65-48f8-9b22-96982c7ac432.png)

When you source init.vim again:
![image](https://user-images.githubusercontent.com/97525037/200771397-ab6a093e-e752-44d3-8471-965c7a44483f.png)

If you change the order of:
```vim
let g:dracula_colorterm = 0
colorscheme dracula
```
You will get the correct colouring when you open without the need to source it again :relaxed: 

I did not try applying other themes, so it might be related to them too

**Comment by avelino** [comment]
@nikola-jokic do you send the change by pull request ?

**Comment by nikola-jokic** [comment]
Hey @avelino,

No, I did not know the scope in which you want this change to be. Maybe it affects multiple themes so I was unsure how would the maintainers like to approach this :relaxed:

**Comment by cassiobotaro** [comment]
Thanks @nikola-jokic to report!
