### ISSUE TITLE
`:Gbrowse` command has been removed

### ISSUE THREAD

**Issue by IvanJijon** [editor-bootstrap/vim-bootstrap#431]
- Vim bootstrap version(number in first line): 2022-12-07 02:54:26
- Operating system: Arch
- Vim/Nvim version: NVIM v0.8.0
- Languages: vimscript

## Description

In the generated script there is a mapping in order to open current line on GitHub:

```
"" Open current line on GitHub
nnoremap <Leader>o :.Gbrowse<CR>
```
But when using it there is an error message:
`":Gbrowse has been removed in favor of :GBrowse"`

**Comment by cassiobotaro** [comment]
Closed by #432
