### ISSUE TITLE
Theme picker

### ISSUE THREAD

**Issue by avelino** [editor-bootstrap/vim-bootstrap#80]
Support multi theme (colors).

In web interface put theme picker.

**Comment by lerrua** [comment]
:+1:

**Comment by tvn87** [comment]
:+1:

**Comment by lerrua** [comment]
@tvn87 or disable this in `.vimrc.local`

**Comment by lerrua** [comment]
@avelino may we can use some things like this:
http://cocopon.me/app/vim-color-gallery/

And a colorscheme editor like vivify: http://bytefluent.com/vivify/

**Comment by tvn87** [comment]
I have been unable to find a way disabling the colorscheme in `.vimrc.local`. Since it is defined in `.vimrc` and there seems to be no `colorscheme disable` command.

**Comment by gilsondev** [comment]
The suggestion is a plugin to choose themes installed?

**Comment by avelino** [comment]
A group of option in the web interface for staff select the theme (vim color) that you want.

**Comment by lerrua** [comment]
@tvn87 may `:syntax off`?

**Comment by tvn87** [comment]
@lerrua I am not talking about the syntax highlight. A theme overrides the
colorscheme I've set in the terminal. So I have `:syntax on` and no theme but
still color ;-). The only way to override a theme in vim is to load a new
theme, but that is something I don't want.

**Comment by di3goleite** [comment]
Or this colorscheme editor: https://terminal.sexy/

**Comment by niko** [comment]
I prefer a light color theme. At least a setting for dark or light would be nice.

**Comment by andreepratama27** [comment]
I've use vim bootstrap. But when I download a theme and paste into 'init.vim', the theme that i download before wasn't work perfectly. Font color change, but not the background. Any solution?

**Comment by cassiobotaro** [comment]
solved with 6d9850259db00337c26469897bf7993e9ecb89e9

**Comment by cassiobotaro** [comment]
We can improve our frontend asap.
